### ISSUE TITLE
Revisar el sistema de temas del mapa

### ISSUE THREAD

**Issue by benjavicente** [open-source-uc/UbiCate-v2#195]
Me llamó la atención como está implementado los temas.

https://github.com/open-source-uc/UbiCate-v2/blob/3882a9b0e8c7f78d81ea5b665da1e6490dae2970/app/hooks/useThemeObserver.tsx#L5-L30

¿Por qué  es el hook que dicta el estilo del mapa? ¿No debería ser al revés?

https://github.com/open-source-uc/UbiCate-v2/blob/3882a9b0e8c7f78d81ea5b665da1e6490dae2970/app/components/darkModeSelector.tsx#L5-L40

Este botón tiene mucha responsabilidad, yo haría que solo cambie le tema y no se preocupe de sincronizarlo.

---

Yo lo que recomendaría es cambiarlo para que sea como estos selectores de 3 estados: tema del dispositivo, dark mode, light mode.

1. Crear un contexto global del tema. 

Hacer un contexto de theme, donde se exponga el estado del tema actual (que depende de la clase dark o del prefers-color-scheme si es que no está la clase), y una función que cambie el tema a light, dark o reiniciar(null) que permita modificar la clase que modifica el tema.

El botón para cambiar el estilo usuarioa esta función, y cualquier js que requiera el tema actual, lo podría sacar de este hook.

2. Aprovechar el css para definir cambios de colores (esto no está probado)

```css
:root:not(.dark) {
  --bg-color: white;
  --text-color: black;
}

@media (prefers-color-scheme: dark) {
  :root:not(.light) {
    --bg-color: black;
    --text-color: white;
  }
}
```
